import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Georama } from "next/font/google"; // import all fonts
import "./globals.css";
import Provider from "./component/Provider";
import Loading from "./loading";
import { Suspense } from "react";
import NavBar from "./component/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ['400', '700'], // add weights you need
});

const georama = Georama({
  variable: "--font-georama",
  subsets: ["latin"],
  weight: ['400', '700'], // add weights you want
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased`}
        // style={{ fontFamily: "var(--font-lato)" }} // apply Lato globally for body
      >
        <Suspense fallback={<Loading />}>
          <Provider>
            {/* <NavBar /> */}
            {children}
          </Provider>
        </Suspense>
      </body>
    </html>
  );
}
